import 'musica.dart';

class MusicaController{

  late List<Musica> musicas;

  MusicaController(){
    musicas=[
      Musica(nome: "Stronger", artista: "Cat Dealers Feat. HRRTZ"),
      Musica(nome: "Let’s Love", artista: "David Guetta Feat. Sia"),
      Musica(nome: "Guess I Was Wrong", artista: "Rooftime"),
      Musica(nome: "Alive (It Feels Like)", artista: "Alok"),
      Musica(nome: "Let Me Go", artista: "Alok & KSHMR feat. MKLA"),
      Musica(nome: "Paradise",artista: "Alan Walker Feat. K-391 e Boy in Space"),
      Musica(nome: "Don’t You Hold Me Down", artista: "Alan Walker Feat. Georgia Ku"),
      Musica(nome: "Han Han Han", artista: "Groove Delight"),
      Musica(nome: "Tina", artista: "Vintage Culture Feat. Bhaskar, Meca"),
      Musica(nome: "Guatemala", artista: "Froid"),
      Musica(nome: "Ocean", artista: "Alok, Zeeba e IRO"),
      Musica(nome: "Headlights", artista: "Alok e Alan Walker Feat. KIDDO"),
      Musica(nome: "Snap", artista: "Rosa Linn Feat. Luca Schreiner"),
      Musica(nome: "The Business", artista: "Tiësto"),
      Musica(nome: "Good Times", artista: "Gabe Feat. Tough Art"),
      Musica(nome: "Come With Me", artista: "Carola"),
      Musica(nome: "Agape", artista: "Vintage Culture"),
      Musica(nome: "Alive", artista: "Franky Wah Feat. Vintage Culture"),
      Musica(nome: "No Love", artista: "Reezer e Antdot Feat. Michael Nicholas"),
      Musica(nome: "It’s a Beautiful Day", artista: "TRINIX Feat. Rushawn"),
      Musica(nome: "Closer", artista: "Ashibah Feat. BAKKA"),
      Musica(nome: "Party On My Own", artista: "Alok, Vintage Culture"),
      Musica(nome: "We Can Come Together", artista: "Love Regenerator Feat. Calvin Harris e Eli Brown"),
      Musica(nome: "Only You", artista: "Alesso Feat. Sentinel"),
      Musica(nome: "Work With My Love", artista: "Alok Feat. James Arthur"),
      Musica(nome: "Other Boys", artista: "Marshmello Feat. Dove Cameron"),
      Musica(nome: "In My Mind", artista: "Alok Feat. John Legend"),
      Musica(nome: "Alone", artista: "Alok Feat. ALOTT e APOPHIS"),
      Musica(nome: "Another Love", artista: "Tom Odell Feat. Tiësto"),
      Musica(nome: "Kill Me", artista: "Alok"),
      Musica(nome: "Amanhã", artista: "Vintage Culture"),
      Musica(nome: "Unloved", artista: "Ciacco"),
      Musica(nome: "Always Feel Like", artista: "Alok"),
      Musica(nome: "Gone Are The Days", artista: "Kygo Feat. James Gillespie"),
      Musica(nome: "Love Runs Out", artista: "Martin Garrix Feat. G-Eazy e Sasha Alex Sloan"),
      Musica(nome: "Burning Up", artista: "Liu"),
      Musica(nome: "15 Miles", artista: "Evokings Feat. Thauper"),
      Musica(nome: "Keep Walking", artista: "Alok Feat. Rooftime"),
      Musica(nome: "Oi Oi Oi", artista: "Dubdogz Feat. Maxximal, MC Hollywood"),
      Musica(nome: "Yesterday", artista: "Tiësto"),
      Musica(nome: "Somos", artista: "Melim Feat. Alok"),
      Musica(nome: "Povoada", artista: "Samhara Feat. Double MZK e Sued Nunes"),
      Musica(nome: "You", artista: "Alex D’Rosso Feat. ZHIKO e PHARAØH"),
      Musica(nome: "Tell Me Something", artista: "Malifoo"),
      Musica(nome: "Steal Your Love", artista: "KVSH, Bruno Be, Fagin"),
      Musica(nome: "Free", artista: "Vintage Culture Feat. Fancy Inc Roland Clark"),
      Musica(nome: "Easy", artista: "Öwnboss Feat. Daft Hill"),
      Musica(nome: "LSD", artista: "Will Sparks Feat. New World Sound"),
      Musica(nome: "The Groov", artista: "Illusionize Feat. Dual Channels"),
      Musica(nome: "Without You", artista: "David Guetta Feat. Usher"),
      Musica(nome: "Rock The Casbah", artista: "Vintage Culture"),
      Musica(nome: "Happy Hour", artista: "Felix Cartal x Kiiara"),
      Musica(nome: "I’m Into It", artista: "Paul Oakenfold Feat. ZHU e Velvet Cash"),
      Musica(nome: "Give It Up", artista: "Firebeatz Feat. Dubdogz"),
      Musica(nome: "Sleepwalking", artista: "Dubdogz Feat. Bruno Be, Ghostt, The Chain Gang of 1974"),
      Musica(nome: "Mami Mami", artista: "Alok"),
      Musica(nome: "Ready Set Go", artista: "Alok"),
      Musica(nome: "Lasting Lover", artista: "Sigala Feat. James Arthur"),
      Musica(nome: "Hear Me Say", artista: "Jonas Blue Feat. LÉON"),
      Musica(nome: "Rather Be", artista: "Dubdisko"),
      Musica(nome: "Attitude", artista: "Bruno Martini Feat. Kicks"),
      Musica(nome: "Oohla Oohla", artista: "Tiësto Feat. Lucas e Steve"),
      Musica(nome: "Pimenta", artista: "Dennis Feat. Bruno e Marrone"),
      Musica(nome: "Swimming In Your Eyes", artista: "Dynoro"),
      Musica(nome: "Be Someone", artista: "KVSH Feat. Schillist e Ray X Ben"),
      Musica(nome: "Agape", artista: "Vintage Culture"),
      Musica(nome: "Belly Dancer", artista: "Imanbek Feat. BYOR"),
      Musica(nome: "Erva da Jamaica", artista: "Vegas Feat. Coktel Molotov"),
      Musica(nome: "I Can’t Wait", artista: "Tiësto Feat. Solardo"),
      Musica(nome: "Here We Go Again", artista: "Oliver Tree Feat. David Guetta"),
      Musica(nome: "Debouch", artista: "FLIP"),
      Musica(nome: "Baby Don’t Hurt Me", artista: "David Guetta Feat. Anne-Marie, Coi Leray"),
      Musica(nome: "Used To Be", artista: "Steve Aoki and Kiiara"),
      Musica(nome: "100 Degrees", artista: "Dubdogz, Bhaskar, Calmani & Grey"),
      Musica(nome: "Later", artista: "Zerky"),
      Musica(nome: "Tequila", artista: "Mariana BO Feat. Jetlag Music e Lazy Bear"),
      Musica(nome: "Party Girl", artista: "Breaking Beattz Feat. Touch The Mind"),
      Musica(nome: "For Me", artista: "Zuffo Feat. Vektor e The Pups"),
      Musica(nome: "Otherside", artista: "Reezer"),
      Musica(nome: "You Get", artista: "Volkoder Feat. Dubdogz"),
      Musica(nome: "Serotonin Moonbeams", artista: "The Blessed Madonna"),
      Musica(nome: "Fractions", artista: "Vintage Culture"),
      Musica(nome: "Sorri, Sou Rei", artista: "KVSH Feat. Natiruts"),
      Musica(nome: "Anunciação", artista: "Alceu Valença"),
      Musica(nome: "Turn Me On", artista: "David Guetta Feat. Nicki Minaj"),
      Musica(nome: "Distant Memory", artista: "R3HAB, Timmy Trumpet, W&W"),
      Musica(nome: "Goes Around", artista: "Jetlag, Santti e Jay Jenner"),
      Musica(nome: "Ghost", artista: "Bruno Martini"),
      Musica(nome: "Lullaby", artista: "Flakkë Feat. Gudi e Luisah"),
      Musica(nome: "Out Out", artista: "Joel Corry e Jax Jones Feat. Charli XCX e Saweetie"),
      Musica(nome: "Banzai", artista: "Maz Feat. Bhaskar"),
      Musica(nome: "Only Me", artista: "Zuffo Feat. Voltech"),
      Musica(nome: "Bad Vibes", artista: "Almanac Feat. Raiid"),
      Musica(nome: "I Got A Feeling", artista: "Felix Jaehn e Robin Schulz Feat. Georgia Ku"),
      Musica(nome: "Butterflies", artista: "Vintage Culture, FFlora e Meca Feat. Tristan Henry"),
      Musica(nome: "Baby", artista: "INNA"),
      Musica(nome: "Underground", artista: "Almanac Feat. Victor Cronos"),
      Musica(nome: "Eu Vou", artista: "Dennis Feat. Luan Santana"),
      Musica(nome: "Hours and Hours", artista: "Bhaskar"),
      Musica(nome: "Clara", artista: "Fred again"),
    ];
  }

}